### ISSUE TITLE
20210524/リアクティビティクイズ

### ISSUE THREAD

**Issue by knj4484** [svelte-jp/quiz#3]
## テーマ

- リアクティブ宣言について
  - https://sveltejp.dev/tutorial/reactive-declarations
  - https://sveltejp.dev/tutorial/reactive-statements
- オブジェクトの更新について
  - https://sveltejp.dev/tutorial/updating-arrays-and-objects

（チュートリアルから問題を作ると、見出しに一致させるというのが出来ませんでした^^;）
## Discordチャンネルへの問題投稿に関する希望

- 自分で投稿したい

（現状のIssueテンプレートにはないのですが、実験的に追加してみました）
## 問題文

Svelteのリアクティビティについて、以下のうち間違っているものはどれでしょう？

A ブロック（`{ }`）に入れることで複数の文をリアクティブに出来る
B `obj.foo += 1`という代入によって、`obj.foo`を参照している部分が更新される
C ifブロック（`if(){ }`）をリアクティブに出来る
D リアクティブな文は、`$;`を使って宣言する

## 回答と解説

正解はDです。

解説は下記のドキュメントをご参照ください。
リアクティブ宣言について
https://sveltejp.dev/tutorial/reactive-declarations
https://sveltejp.dev/tutorial/reactive-statements

オブジェクトの更新について
https://sveltejp.dev/tutorial/updating-arrays-and-objects

**Comment by myLifeAsaDog** [comment]
A の「ブロック」とは、下記のような「`$:`ブロック」のことを指してますか？

```javascript
let hoge, hoge2, fuga = 3

$:{
  hoge = fuga+1
  hoge2 = fuga+2
}
```

そして C は下記のように「`$:`ブロックには if 文も書ける」という意味であってますか？

```javascript
let message

$: if (num < 10) {
  message = 'num is less 10'
}
```

**Comment by myLifeAsaDog** [comment]
あ、ちなみに「Discordチャンネルへの問題投稿に関する希望」は、テンプレート追加しちゃっていいと思います！

**Comment by knj4484** [comment]
> A の「ブロック」とは、下記のような「`$:`ブロック」のことを指してますか？

そうです

> そして C は下記のように「`$:`ブロックには if 文も書ける」という意味であってますか？

こちらもその通りです

**Comment by myLifeAsaDog** [comment]
なるほど、どちらもチュートリアルだと文章とコードがセットで説明されているので理解できるのですけど、

A に関しては文章で「ブロック」だけだと指し示すものが広すぎるので `$:ブロック` とか `$:{}` とかの方がより良くないですかね？
また C の方に関しても「`if`ブロック」だとテンプレート構文の `{#if}` と混同してややこしいので、`if 文` などの方が適切なように思いますが
どうでしょうか？

**Comment by knj4484** [comment]
ご指摘頂いた点について、以下のことも踏まえつつ書き直してみました

- `$:`を選択肢Aで書いてしまうと、選択肢Dの意味がなくなってしまう
- if文にはブロックを伴わない書き方もあり、その場合はリアクティブにできない（未検証）

**Comment by myLifeAsaDog** [comment]
修正してもらった内容で大丈夫そうです！

ちなみに下記の内容で動くので、れはこれで問題にすればよさそうですね。

```javascript
<script>
  let count = 0
  let message = ''
	
  $: if (count < 10) message = 'num is less 10'
  $: if (count > 10) message = 'num is over 10'
</script>

<p>{message}</p>
<button on:click={() => { count++ }}>Clicked {count} times</button>
```

**Comment by myLifeAsaDog** [comment]
上記で問題ありませんので、2021/05/24の投稿をお願いします！

**Comment by knj4484** [comment]
では、明日これで投稿します。
コードの検証もありがとうございました！

**Comment by knj4484** [comment]
下記リンクのメッセージで投稿しました
https://discord.com/channels/777141291800723468/844153920241664041/846181370190495814
