### ISSUE TITLE
20210602/ $:クイズ

### ISSUE THREAD

**Issue by myLifeAsaDog** [svelte-jp/quiz#4]
## テーマ
`$:` 接頭辞（リアクティビティ）

## 問題文
下記のうち、`count` の変化に対して `message` がリアクティブにならないものはどれでしょう？

A
```javascript
$: if (count <= 10) { message = 'less 10' } else { message =  'over 10' }
```
B
```javascript
$: message = (count) => { return count }
```
C
```javascript
$: switch(true) {
  case count <= 3:
    message = 'less 3'
    break
  default:
    message = 'over 3'
    break
}
```
D
```javascript
$: count <= 5 ? message = 'less 5' : message = 'over 5' 
```

## 回答と解説

正解は B です！

`$:` についてはこちら
https://sveltejp.dev/docs#3_$

## Discordチャンネルへの問題投稿に関する希望
自分で投稿可能ですが、特にこだわりはありません

**Comment by myLifeAsaDog** [comment]
リアクティビティの問題が続くのもなんなので、投稿日は調整します。

**Comment by knj4484** [comment]
スペース消しませんか？
```
$:  message = (count ) => { return count }
$: message = (count) => { return count }
```

`$:`自体は接頭辞と呼ぶよりも（JavaScriptの「ラベル」なので）「`$:`ラベル」または単に「`$:`」と書く方が個人的にはしっくり来ると思います。

Bが間違っているかどうかは目的によるような気がしますので、以下のような問題文はどうでしょうか？

> 下記のうち、`count`の変化に対して`message`がリアクティブにならないものはどれでしょう？

**Comment by myLifeAsaDog** [comment]
修正しました！

**Comment by knj4484** [comment]
ありがとうございます。
良さそうです。
では、これでよろしくお願いします！
