### ISSUE TITLE
20210528/{@debug}クイズ

### ISSUE THREAD

**Issue by knj4484** [svelte-jp/quiz#6]
## テーマ

- [{@debug ...}](https://sveltejp.dev/docs#debug)

## Discordチャンネルへの問題投稿に関する希望

- 自分で投稿したい

## 問題文

`{@debug ...}` タグのうち正しくコンパイルされるものはどれでしょう？

A `{@debug users[0]}`
B `{@debug user1.name}`
C `{@debug user1, user2}`
D `{@debug user1.name === user2.name}`

## 回答と解説

正解はCです。
解説は下記のドキュメントをご参照ください。
https://svelte.dev/docs#debug

**Comment by tomoam** [comment]
OKです！

これ、今でもたまに `B` を書いてしまうんですよね
